# fly.toml app configuration file generated for queue-app on 2023-09-15T17:17:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "queue-app"
primary_region = "dfw"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
